# Title: Session report

# Description: Assembles a single Rmd holding a methods narrative and the
# nicheR code that reproduces the session, renders it, and delivers both files
# as a zip. The Rmd is the source of truth and the HTML is what you get by
# knitting it, so the two cannot describe different analyses.

# The Rmd is generated whole, YAML included, so there is no template file to
# keep in sync with the generator.

# Date last updated: 08/12/2026


# ASSEMBLY ----------------------------------------------------------------

#' Front matter and setup chunk
#'
#' @returns A character vector of Rmd lines.
#'
#' @noRd
report_preamble <- function(){

  ver <- tryCatch(as.character(utils::packageVersion("nicheR")),
                  error = function(e) "unknown")

  c("---",
    "title: \"nicheR session report\"",
    paste0("date: \"", format(Sys.time(), "%d %B %Y"), "\""),
    "output:",
    "  html_document:",
    "    toc: true",
    "    toc_float: true",
    "    theme: flatly",
    "    highlight: tango",
    "---",
    "",
    "```{r setup, include = FALSE}",
    "knitr::opts_chunk$set(collapse = TRUE, comment = \"#>\")",
    "library(nicheR)",
    "library(terra)",
    "```",
    "",
    "## About this report",
    "",
    paste0("Generated by the nicheR Shiny app on ",
           format(Sys.time(), "%d %B %Y at %H:%M"),
           ", using nicheR version ", ver, "."),
    "",
    "The text below describes the state of the session at the moment this",
    "report was generated, not the order in which things were tried. The code",
    "reproduces that state and can be run on its own.",
    "",
    if(!report_can_eval()){
      c("This session used uploaded files, so the code chunks are shown but",
        "not run. Set `data_dir` in the first chunk to the folder holding",
        "those files and the script will run as written.", "")
    },
    "")
}


#' Assemble the full report
#'
#' Sections for the remaining tabs are appended here as they are written.
#' Reads session_data from the enclosing server environment.
#'
#' @returns A single string of Rmd source.
#'
#' @noRd
report_rmd <- function(){
  paste(c(report_preamble(),
          report_build_section(),
          report_predict_section(),
          report_citation(),
          "## Session information", "",
          "The versions below are those used when this report was generated.",
          "",
          report_chunk("sessionInfo()", label = "session-info", eval = TRUE)),
        collapse = "\n")
}


# DOWNLOAD ----------------------------------------------------------------

output$create_report <- downloadHandler(

  filename = function(){
    paste0("nicheR_report_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".zip")
  },

  contentType = "application/zip",

  content = function(file){

    if(!requireNamespace("rmarkdown", quietly = TRUE)){
      showNotification(instructions$report_needs_rmarkdown,
                       type = "error", duration = 6)
      return()
    }

    withProgress(message = "Building report", value = 0, {

      # render() writes intermediates beside its input, so it gets a directory
      # of its own rather than the shared tempdir
      dir <- file.path(tempdir(), paste0("nicheR_report_",
                                         format(Sys.time(), "%H%M%S")))
      dir.create(dir, recursive = TRUE, showWarnings = FALSE)
      on.exit(unlink(dir, recursive = TRUE), add = TRUE)

      rmd <- file.path(dir, "nicheR_report.Rmd")

      incProgress(0.2, detail = "writing script")
      writeLines(report_rmd(), rmd)

      incProgress(0.3, detail = "rendering")
      html <- tryCatch(
        rmarkdown::render(rmd,
                          output_file = "nicheR_report.html",
                          envir = new.env(parent = globalenv()),
                          quiet = TRUE),
        error = function(e){
          showNotification(paste("The report script could not be rendered:",
                                 e$message,
                                 "The script itself is still included."),
                           type = "warning", duration = 8)
          NULL
        }
      )

      incProgress(0.3, detail = "packaging")

      # zip() stores whatever path it is given, so it runs from inside the
      # directory to keep the archive flat
      old <- setwd(dir)
      on.exit(setwd(old), add = TRUE)

      keep <- c("nicheR_report.Rmd",
                if(!is.null(html)) "nicheR_report.html")

      ok <- tryCatch({
        utils::zip(zipfile = normalizePath(file, mustWork = FALSE),
                   files = keep, flags = "-q")
        TRUE
      }, error = function(e) FALSE)

      # Without a zip binary there is no archive to deliver, so the script is
      # sent on its own rather than failing silently
      if(!ok || !file.exists(file)){
        showNotification(instructions$report_no_zip,
                         type = "warning", duration = 8)
        file.copy("nicheR_report.Rmd", file, overwrite = TRUE)
      }

      incProgress(0.2)
    })
  }
)
