# Title: Session report

# Description: Assembles a single Rmd holding a methods narrative and the
# nicheR code that reproduces the session, and delivers that file as the
# download. The app does not run the script. Knitting the file is what runs
# it, so the download is quick and no uploaded file has to be kept.

# The Rmd is generated whole, YAML included, so there is no template file to
# keep in sync with the generator.

# Date last updated: 10/06/2026


# ASSEMBLY ----------------------------------------------------------------

#' Front matter and setup chunk
#'
#' @returns A character vector of Rmd lines.
#'
#' @noRd
report_preamble <- function(){

  ver <- tryCatch(as.character(utils::packageVersion("nicheR")),
                  error = function(e) "unknown")

  c("---",
    "title: \"nicheR session report\"",
    paste0("date: \"", format(Sys.time(), "%d %B %Y"), "\""),
    "output:",
    "  html_document:",
    "    toc: true",
    "    toc_float: true",
    "    theme: flatly",
    "    highlight: tango",
    "---",
    "",
    "```{r setup, include = FALSE}",
    "knitr::opts_chunk$set(collapse = TRUE, comment = \"#>\")",
    "library(nicheR)",
    "```",
    "",
    "## About this report",
    "",
    paste0("Generated by the nicheR Shiny app on ",
           format(Sys.time(), "%d %B %Y at %H:%M"),
           ", using nicheR version ", ver, "."),
    "",
    "The text below describes the state of the session at the moment this",
    "report was generated, not the order in which things were tried. The code",
    "reproduces that state and can be run on its own.",
    "",
    if(length(session_data$ellipsoid_list) > 0){
      c("Each niche is built as its own object. The steps after that use",
        "`lapply()`, which applies one call to a whole list of niches, so the",
        "arguments are written once instead of repeated. Niches in the same",
        "`lapply()` were given the same arguments; any handled differently get",
        "their own call. Results stay in lists, so later steps can pull out the",
        "piece belonging to each niche by name.", "")
    },
    report_files_block())
}

#' Uploaded files the script reads, and the folder they are read from
#'
#' The browser sends only the name of an uploaded file, never its folder, so
#' the script declares the folder once as data_dir and reads every file from
#' it by name. The chunk stops with the names of any file it cannot find,
#' which is clearer than the first failed read further down.
#'
#' Reads session_data from the enclosing server environment.
#'
#' @returns A character vector of Rmd lines, empty when the session read no
#'   uploaded files.
#'
#' @noRd
report_files_block <- function(){

  mode <- session_data$input_mode

  # Background data, unless it is the example data or there is none
  from_file <- !isTRUE(mode %in% c("example", "virtual"))
  data_files <- if(from_file) as.character(session_data$data_source)

  # Bias layers, read only when a surface was prepared from uploaded ones
  bias_upload <- !identical(mode, "virtual") &&
    !is.null(session_data$prepared_bias) &&
    !identical(session_data$bias_source, "example")
  bias_files <- if(bias_upload) as.character(session_data$bias_source)

  # Sampling masks, recorded on each point set
  occ <- session_data$ellipsoid_point_sets_list
  mask_files <- unlist(lapply(occ, function(sets){
    vapply(sets, function(df) as.character(occ_meta(df, "mask", "none")),
           character(1))
  }))
  mask_files <- mask_files[!is.na(mask_files) & mask_files != "none"]

  files <- unique(c(data_files, bias_files, mask_files))

  if(!from_file && !bias_upload && length(files) == 0) return(character(0))

  # One name read by two steps. Fine when it is the same file, but two
  # different files cannot sit in one folder under one name.
  shared <- unique(c(intersect(data_files, bias_files),
                     intersect(data_files, mask_files),
                     intersect(bias_files, mask_files)))

  code <- c("# Folder holding the files uploaded to the app. Use forward slashes,",
            "# as in \"C:/Users/me/my_data\"",
            "data_dir <- \".\"")

  if(length(files) > 0){
    code <- c(code,
              "",
              "# Stop here, with the names, if a file is not in that folder",
              paste0("data_files <- ", report_chr(files)),
              "not_found <- data_files[!file.exists(file.path(data_dir, data_files))]",
              "if(length(not_found) > 0){",
              "  stop(\"Not found in data_dir: \", paste(not_found, collapse = \", \"))",
              "}")
  }

  if(length(shared) > 0){
    code <- c(code,
              "",
              paste0("# ", paste(shared, collapse = ", "),
                     if(length(shared) == 1) " is" else " are",
                     " read by more than one step below."),
              "# If those were different files that share a name, rename one and",
              "# change its name where it is read.")
  }

  c("## Uploaded files", "",
    "This session used files uploaded to the app. The app records the name of",
    "each file but cannot see the folder it came from, so set `data_dir` below",
    "to the folder holding them. Left as `\".\"`, the script looks in the",
    "folder this file is saved in when it is knitted.", "",
    report_chunk(code, label = "files"))
}

#' Assemble the full report
#'
#' Sections for the remaining tabs are appended here as they are written.
#' Reads session_data from the enclosing server environment.
#'
#' @returns A single string of Rmd source.
#'
#' @noRd
report_rmd <- function(){
  paste(c(report_preamble(),
          report_build_section(),
          report_predict_section(),
          report_bias_section(),
          report_generate_section(),
          report_citation(),
          "## Session information", "",
          "The versions below are those in use when this file is knitted.",
          "",
          report_chunk("sessionInfo()", label = "session-info")),
        collapse = "\n")
}


# DOWNLOAD ----------------------------------------------------------------

# The script is the whole download. Nothing is run here, so the handler only
# writes the file.
output$create_report <- downloadHandler(
  filename = function(){
    paste0("nicheR_report_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".Rmd")
  },
  content = function(file){
    writeLines(report_rmd(), file)
  }
)
